# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Comp"
title_separator: "—"
masthead_title: "Home"
name: "Comp"
email: "onecomputer00@gmail.com"
description: >- # this means to ignore newlines
  Comp's personal website.
  Includes a blog on various topics in programming and a portfolio of cool projects.
github_username: "1Computer1"
url: "https://1computer1.github.io"
baseurl: "/"
minimal_mistakes_skin: "dirt"
search: true
search_full_content: true
logo: "/assets/images/lambda.png"
og_image: "/assets/images/lambda.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /posts/:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
repository: 1Computer1/1computer1.github.io

head_scripts:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Comp"
  bio: >-
    A programmer with an interest in programming languages and types.
    Haskeller for fun.
    Undergraduate at the University of Toronto.
  location: "Toronto, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/1Computer1"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/1Computer1"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      toc: true
      toc_label: "Contents"
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /blog/
